{{- range .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- range $key, $val := .data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  ---
{{- end }}