apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-app.fullname" . }}
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.service.sslCertARN }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port2 }}
      targetPort: http
      protocol: TCP
      name: https
  selector:
    {{- include "ecommerce-app.selectorLabels" . | nindent 4 }}
